vm_admin_password = "P@ssw0rd123!"
location          = "westeurope"
prefix            = "rasdemo"
domain_name       = "rasdemo.local"
ras_installer_url = "https://download.parallels.com/ras/latest/RASInstaller.msi"